{
  pkgs,
  pkgs-unstable,
  inputs,
  ...
}:

{
  home.packages = with pkgs; [
    qt6Packages.qt6ct
    pkgs-unstable.github-copilot-cli
    pkgs-unstable.codex
    pkgs-unstable.claude-code
    inputs.MyNixvim.packages.${pkgs.stdenv.hostPlatform.system}.default
    fzf
    imagemagick
    nodejs
    fastfetch
    btop
    zoxide
    bat
    eza
    ripgrep
    lazygit
    duf
    nix-output-monitor
    wl-clipboard
    xclip
    grim
    slurp
    swayimg
    libheif
    brightnessctl
    pamixer
    pavucontrol
    playerctl
    libdecor
    lenovo-legion
    protonup-qt
    obsidian
    go-musicfox
    pkgs-unstable.typora # 1.14.8 vs 1.13.6 on stable
  ];
}
