;;; early-init.el --- Runs before the UI and package system  -*- lexical-binding: t; -*-

;;; Commentary:
;; Generated by modules/home/programs/dev/emacs/default.nix; the grammar path
;; below is substituted at build time.  Everything here has to happen before
;; Emacs draws its first frame or touches package.el.

;;; Code:

;; `package-enable-at-startup' is deliberately left at t.  The Nix wrapper drops
;; its packages into <profile>/share/emacs/site-lisp/elpa/, which is exactly
;; where `package-activate-all' looks, and that call is the only thing that
;; loads each package's -autoloads.el.  Turning it off puts the packages on the
;; load-path but leaves every autoloaded command void, so `:init' blocks fail
;; with things like "void-function doom-modeline-mode".  Nothing here contacts
;; an archive: that only happens on an explicit `package-refresh-contents'.
;;
;; Installing still goes through default.nix — there is no writable
;; `package-user-dir' for `M-x package-install' to use.
(setq package-install-upgrade-built-in nil)

;; The collector runs at an 800 kB threshold by default, which means dozens of
;; collections while init.el loads.  init.el hands a sane value back on
;; `emacs-startup-hook'.
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6)

;; Frame parameters set here apply to the *first* frame, so the session never
;; flashes a toolbar it is about to remove.  The colours are nord0/nord4, which
;; is what doom-nord settles on a moment later.
(setq default-frame-alist
      '((menu-bar-lines . 0)
        (tool-bar-lines . 0)
        (vertical-scroll-bars . nil)
        (background-color . "#2e3440")
        (foreground-color . "#d8dee9")))

;; Emacs otherwise resizes the frame once per font or UI-element change during
;; startup, and each resize is a round trip to the compositor.
(setq frame-inhibit-implied-resize t)

;; Tree-sitter grammars live in the Nix store.  Emacs 30 ships the *-ts-mode
;; major modes but no grammars, and only looks here and in
;; `user-emacs-directory'/tree-sitter.
(setq treesit-extra-load-path (list "@treesitGrammars@"))

;; init.el is a read-only /nix/store symlink, so Customize must be pointed at a
;; writable file or every `M-x customize' write fails.  It is loaded near the
;; end of init.el.
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))

;;; early-init.el ends here
